# Generated by Django 5.0.6 on 2024-05-19 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('state', models.CharField(choices=[('cancelada', 'Cancelada'), ('finalizada', 'Finalizada'), ('pendiente', 'Pendiente')], default='finalizada', max_length=120)),
                ('purchase_date', models.DateTimeField(auto_now_add=True, help_text='Fecha de compra')),
                ('delivery_date', models.DateField(blank=True, help_text='Fecha de entrega', null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='inventory_management.supplier')),
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'db_table': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Cantidad de productos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='inventory_management.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing_management.purchase')),
            ],
            options={
                'verbose_name': 'elemento de la compra',
                'verbose_name_plural': 'elementos de la compra',
                'db_table': 'PurchaseItems',
            },
        ),
    ]
